project:
  type: website
  pre-render:
    - pysym2md --output_file apilist.txt slmn
  post-render:
    - llms_txt2ctx llms.txt --optional true --save_nbdev_fname llms-ctx-full.txt
    - llms_txt2ctx llms.txt --save_nbdev_fname llms-ctx.txt
  resources:
    - "*.txt"

format:
  html:
    theme:
      dark: [cosmo, darktheme.scss]
      light: cosmo
    highlight-style:
      light: arrow
      dark: dracula
    css: styles.css
    include-after-body: theme-toggle.html
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: dark
    search: true
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]