# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slmn',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/slmn',
                'lib_path': 'slmn'},
  'syms': {'slmn.core': {'slmn.core.foo': ('core.html#foo', 'slmn/core.py')}}}
