"""Async file-based IPC: one side `drop()`s a file, another side -- possibly a different process, possibly a different machine reachable only via a synced/shared directory (Dropbox, rsync, an NFS mount, ...) -- `pickup()`s it later, no direct connection between the two required. Named after the spy tradecraft term. This is the "agent-loop file relay" deferred out of `02_remote.ipynb`'s original scope, now built out on its own -- and it subsumes an earlier hand-rolled prototype (`cycle.sh`/`watch.sh`, a bash-only prompt/response relay used to drive a Claude Code session from a Jupyter cell on a different machine) whose good ideas are generalized here: Maildir's atomic-rename trick (`drop()`/`pickup()`), and blocking-wait-on-mtime-change (`watch()`, `next_prompt()`) -- reimplemented in Python rather than shelled out to `stat`, because bash's 1-second mtime resolution left a real race between "checked, nothing pending" and "started waiting for the next change" (found the hard way: a drop landing in that gap could be missed forever).

Docs: https://drscotthawley.github.io/slmn/dead_drop.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_dead_drop.ipynb.

# %% auto #0
__all__ = ['drop', 'pickup', 'watch', 'list_sessions', 'drop_bundle', 'read_bundle', 'pickup_bundle', 'watch_session',
           'drop_prompt', 'reply_bundle', 'await_reply', 'pending_replies', 'complete_reply', 'unprocessed_replies',
           'next_prompt', 'StreamWriter', 'stream']

# %% ../nbs/05_dead_drop.ipynb #2d949541
import re, time, uuid, os, shutil
from pathlib import Path
from .nbtools import _resolve_safe

# %% ../nbs/05_dead_drop.ipynb #9a1f3c02
_SESSION_ID = None  # per-process fallback, generated at most once

def _session_id() -> str:
    "Resolve the current session id: the `CLAUDE_CODE_SESSION_ID` env var if set, else a random id generated once and cached for the life of this process (so repeated calls in the same process reuse the same dead-drop subdirectory)."
    global _SESSION_ID
    env_id = os.environ.get('CLAUDE_CODE_SESSION_ID')
    if env_id: return env_id
    if _SESSION_ID is None:
        _SESSION_ID = uuid.uuid4().hex[:12]
    return _SESSION_ID

# %% ../nbs/05_dead_drop.ipynb #f81b6a3e
import platform, subprocess

def _os_info() -> str:
    "One-line OS description. On Linux this reads /etc/os-release for the distro name (e.g. 'Ubuntu 22.04.4 LTS') -- WSL2 runs a real Linux kernel, so this naturally reports the Linux distro rather than the Windows host, which is what actually matters here. On macOS, reports 'macOS <version>'. Falls back to platform.system() otherwise."
    system = platform.system()
    if system == 'Darwin':
        return f"macOS {platform.mac_ver()[0]}"
    if system == 'Linux':
        os_release = Path('/etc/os-release')
        if os_release.exists():
            info = dict(l.split('=', 1) for l in os_release.read_text().splitlines() if '=' in l)
            pretty = info.get('PRETTY_NAME', '').strip('"')
            if pretty: return pretty
        return 'Linux'
    return system

def _gpu_info() -> tuple:
    "GPU name(s) and total VRAM (in GB, one decimal place) via nvidia-smi, as two semicolon-joined strings, parallel across multiple GPUs -- ('none detected', 'none detected') if nvidia-smi isn't available or reports nothing."
    which = subprocess.run(['which', 'nvidia-smi'], capture_output=True, text=True).stdout.strip()
    if not which: return "none detected", "none detected"
    r = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total', '--format=csv,noheader,nounits'],
                        capture_output=True, text=True)
    rows = [l.strip() for l in r.stdout.strip().splitlines() if l.strip()]
    if r.returncode != 0 or not rows: return "none detected", "none detected"
    names, vrams = [], []
    for row in rows:
        name, mib = (p.strip() for p in row.rsplit(',', 1))
        names.append(name)
        vrams.append(f"{round(float(mib) / 1024, 1)} GB")
    return "; ".join(names), "; ".join(vrams)

def _machine_info_md() -> str:
    "Compose the MACHINE_INFO.md contents describing this machine: hostname, OS, CPU count, total RAM, GPU name(s), and VRAM (see _os_info, _gpu_info)."
    try:
        ram_gb = round(os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES') / (1024 ** 3), 1)
        ram = f"{ram_gb} GB"
    except (ValueError, OSError):
        ram = "unknown"
    gpu_name, gpu_vram = _gpu_info()
    return (
        "# Machine Info\n\n"
        f"- Hostname: {platform.node()}\n"
        f"- OS: {_os_info()}\n"
        f"- CPUs: {os.cpu_count()}\n"
        f"- RAM: {ram}\n"
        f"- GPU: {gpu_name}\n"
        f"- VRAM: {gpu_vram}\n"
    )

def _write_machine_info(parent_dir:Path) -> None:
    "Write MACHINE_INFO.md into parent_dir if it doesn't already exist (first watch()er on this machine wins; later ones leave it alone)."
    path = parent_dir / "MACHINE_INFO.md"
    if not path.exists():
        path.write_text(_machine_info_md())

# %% ../nbs/05_dead_drop.ipynb #837e642b
def drop(dir:str, # directory to drop into (created if it doesn't exist)
         content:str, # the drop's body
         name:str=None # filename to use; default is a sortable `{timestamp}-{uuid8}` so pickups see drops in creation order
         ) -> str:
    "Atomically write a dead drop into `dir`, for another process -- possibly on another machine, via a synced/shared directory -- to `pickup()` or `watch()` later. Writes to a temp file in the same directory first, then atomically renames it into place (Maildir's trick), so a concurrent pickup/watch never sees a half-written drop. Returns the dropped file's final path."
    dir_ = Path(_resolve_safe(dir))
    dir_.mkdir(parents=True, exist_ok=True)
    fname = name or f"{time.time_ns()}-{uuid.uuid4().hex[:8]}"
    tmp = dir_ / f".tmp-{uuid.uuid4().hex}"
    tmp.write_text(content)
    final = dir_ / fname
    tmp.rename(final)
    return str(final)

# %% ../nbs/05_dead_drop.ipynb #e7916b04
def pickup(dir:str, # directory to check for drops
           delete:bool=True # remove the file after reading it, so each drop is picked up exactly once
           ) -> dict: # {'path':..., 'name':..., 'content':...}, or None if nothing's pending
    "Look for the oldest pending drop in `dir` (sorted by filename, so default drop() names -- timestamp-prefixed -- come out in creation order) and read it. Returns None if `dir` doesn't exist or has no drops. Ignores hidden files -- both its own in-progress temp files (`.tmp-*`) and stray dotfiles from other processes sharing the directory (e.g. an editor's `.foo.swp` if something's being edited in place there)."
    dir_ = Path(_resolve_safe(dir))
    if not dir_.exists(): return None
    candidates = sorted(f for f in dir_.iterdir() if f.is_file() and not f.name.startswith('.'))
    if not candidates: return None
    f = candidates[0]
    content = f.read_text()
    if delete: f.unlink()
    return {'path': str(f), 'name': f.name, 'content': content}

# %% ../nbs/05_dead_drop.ipynb #42a95f92
def _await_change(path:str, # file or directory to watch
                  poll_interval:float, # seconds between mtime checks
                  since:float=None # baseline mtime to compare against; if the path is already newer than this, returns immediately (closes the check-then-wait race -- pass the mtime you observed *before* you checked for existing content, not after)
                  ) -> None:
    "Block until `path`'s mtime is newer than `since` (default: newer than its mtime at call time). Waits for `path` to exist first if it doesn't yet."
    path_ = Path(path)
    while not path_.exists():
        time.sleep(poll_interval)
    base = since if since is not None else path_.stat().st_mtime
    while path_.stat().st_mtime <= base:
        time.sleep(poll_interval)

# %% ../nbs/05_dead_drop.ipynb #55f3628d
def watch(dir:str, # parent directory for drops; a session-scoped subdirectory is created (or reused) under it -- see module docs
          callback:callable, # called as callback(drop) for each drop, where drop is the dict pickup() returns
          poll_interval:float=1.0, # seconds between mtime checks while dir is empty
          delete:bool=True, # remove each drop after callback returns (passed through to pickup)
          max_iters:int=None, # stop after this many drops-or-idle-checks (mainly for tests/scripted runs -- omit to run forever)
          session_id:str=None # session id whose subdirectory to watch; default auto-detects (see _session_id)
          ) -> int:
    "Blocking loop: repeatedly pickup() drops from a session-scoped subdirectory of `dir` and pass each to `callback`; when that subdirectory is empty, blocks on its mtime change (see _await_change) instead of busy-polling pickup() itself. The subdirectory is named after `session_id` (or the auto-detected current session id if omitted), created if it doesn't exist yet or reused as-is if it does -- so multiple agents watching the same parent `dir` don't see each other's drops. Also writes MACHINE_INFO.md into `dir` itself the first time any session watches there (see _write_machine_info) -- a no-op on later calls once it exists. Runs forever unless `max_iters` is given -- stop it with Ctrl-C otherwise. Like slmn's other blocking primitives, this is CLI/import-only, never exposed over MCP, since it never returns promptly. Returns the number of drops processed."
    parent_ = Path(_resolve_safe(dir))
    parent_.mkdir(parents=True, exist_ok=True)
    _write_machine_info(parent_)
    dir_ = parent_ / (session_id or _session_id())
    dir_.mkdir(parents=True, exist_ok=True)
    n, iters = 0, 0
    while max_iters is None or iters < max_iters:
        base = dir_.stat().st_mtime  # captured before pickup(), so a drop landing right here is still caught below
        d = pickup(str(dir_), delete=delete)
        if d is not None:
            callback(d)
            n += 1
        else:
            _await_change(str(dir_), poll_interval, since=base)
        iters += 1
    return n

# %% ../nbs/05_dead_drop.ipynb #c2e4a9d7
def list_sessions(dir:str # parent dead-drop directory (the same `dir` passed to watch())
                   ) -> list: # sorted list of session-id subdirectory names; [] if `dir` doesn't exist
    "List the session ids currently present as subdirectories of `dir` -- i.e. sessions that have called watch(dir, ...) here at least once -- so a producer can pick one to drop() into. Sorted alphabetically. Ignores hidden/dotted entries and non-directories."
    dir_ = Path(_resolve_safe(dir))
    if not dir_.exists(): return []
    return sorted(p.name for p in dir_.iterdir() if p.is_dir() and not p.name.startswith('.'))

# %% ../nbs/05_dead_drop.ipynb #e5c1a7d3
def _prompt_id(text:str="" # representative text to derive the human-readable slug from (e.g. the prompt itself); safe to omit
                ) -> str:
    "Generate a bundle id: `{timestamp}-{slug}-{rand}`. The timestamp leads so bundle directories still sort chronologically (same reasoning as drop()'s default filename); `slug` is the first 6 lowercase alnum characters that survive stripping everything else out of `text` (falls back to 'prompt' if nothing survives, e.g. text that's empty or all-emoji) for a human-skimmable `ls`; `rand` is a short hex suffix (uuid4, same convention as drop()'s default filename) disambiguating same-second collisions."
    ts = time.strftime('%Y%m%dT%H%M%S')
    slug = re.sub(r'[^a-z0-9]', '', text.lower())[:6] or 'prompt'
    rand = uuid.uuid4().hex[:6]
    return f"{ts}-{slug}-{rand}"


# %% ../nbs/05_dead_drop.ipynb #f6d2b8e4
def drop_bundle(dir:str, # directory to drop the bundle into (created if it doesn't exist)
                 files:dict, # {filename: content}, content str or bytes
                 bundle_id:str=None # bundle directory name; auto-generated (see _prompt_id) from the first str-valued file's content if omitted
                 ) -> str: # path to the bundle directory
    "Atomically drop a multi-file bundle -- e.g. a prompt's text plus an image attachment -- as a single directory under `dir`. Writes every file into a hidden temp directory first, then atomically renames the whole directory into place (extends drop()'s Maildir trick to a whole bundle), so a concurrent pickup/watch never sees a partially-written bundle. Returns the bundle's final directory path."
    dir_ = Path(_resolve_safe(dir))
    dir_.mkdir(parents=True, exist_ok=True)
    if bundle_id is None:
        text = next((v for v in files.values() if isinstance(v, str)), "")
        bundle_id = _prompt_id(text)
    tmp = dir_ / f".tmp-{uuid.uuid4().hex}"
    tmp.mkdir()
    for fname, content in files.items():
        if isinstance(content, bytes): (tmp / fname).write_bytes(content)
        else: (tmp / fname).write_text(content)
    final = dir_ / bundle_id
    tmp.rename(final)
    return str(final)

def read_bundle(path:str # a bundle directory, as written by drop_bundle
                 ) -> dict: # {filename: content}, text decoded where possible, else raw bytes
    "Read every file in a bundle directory into {filename: content}, decoding as text where possible and falling back to raw bytes for anything that isn't (e.g. an image attachment)."
    dir_ = Path(path)
    files = {}
    for f in sorted(dir_.iterdir()):
        if not f.is_file() or f.name.startswith('.'): continue
        try: files[f.name] = f.read_text()
        except UnicodeDecodeError: files[f.name] = f.read_bytes()
    return files

def pickup_bundle(dir:str, # directory to check for bundles
                   move_to:str=None # if given, the bundle directory is atomically moved here (same name) instead of being deleted -- e.g. inbox -> received
                   ) -> dict: # {'id':..., 'path':..., 'files':...}, or None if nothing's pending
    "Look for the oldest pending bundle directory in `dir` (sorted by name, so timestamp-led bundle ids -- see _prompt_id -- come out in creation order) and read it (see read_bundle). Returns None if `dir` doesn't exist or has no bundles. If `move_to` is given, atomically renames the bundle directory there instead of deleting it -- marking it claimed without discarding it."
    dir_ = Path(_resolve_safe(dir))
    if not dir_.exists(): return None
    candidates = sorted(p for p in dir_.iterdir() if p.is_dir() and not p.name.startswith('.'))
    if not candidates: return None
    bundle_dir = candidates[0]
    files = read_bundle(bundle_dir)
    path = str(bundle_dir)
    if move_to:
        move_dir = Path(_resolve_safe(move_to))
        move_dir.mkdir(parents=True, exist_ok=True)
        dest = move_dir / bundle_dir.name
        bundle_dir.rename(dest)
        path = str(dest)
    else:
        shutil.rmtree(bundle_dir)
    return {'id': bundle_dir.name, 'path': path, 'files': files}

# %% ../nbs/05_dead_drop.ipynb #a9c3e7f5
def watch_session(dir:str, # parent dead-drop directory; a session-scoped inbox/received/outbox is created (or reused) under it
                   callback:callable, # called as callback(bundle) for each prompt bundle picked up (already moved to received/); bundle is the dict pickup_bundle() returns
                   poll_interval:float=1.0, # seconds between mtime checks while inbox/ is empty
                   max_iters:int=None, # stop after this many bundles-or-idle-checks (mainly for tests/scripted runs -- omit to run forever)
                   session_id:str=None # session id whose inbox/received/outbox to use; default auto-detects (see _session_id)
                   ) -> int:
    "Blocking loop, the bundle-aware sibling of watch(): repeatedly pickup_bundle()s prompt bundles from a session-scoped inbox/ subdirectory of `dir`, atomically moving each one to the matching received/ subdirectory (see pickup_bundle's move_to) before passing it to `callback` -- so a bundle sitting in received/ with no same-id bundle in outbox/ (see pending_replies) means it was seen but never answered, e.g. after a crash mid-processing. Also writes MACHINE_INFO.md into `dir` on first use, same as watch(). Runs forever unless `max_iters` is given. Returns the number of bundles processed."
    parent_ = Path(_resolve_safe(dir))
    parent_.mkdir(parents=True, exist_ok=True)
    _write_machine_info(parent_)
    session_dir = parent_ / (session_id or _session_id())
    inbox, received, outbox = session_dir / 'inbox', session_dir / 'received', session_dir / 'outbox'
    for d in (inbox, received, outbox, session_dir / 'completed'): d.mkdir(parents=True, exist_ok=True)
    n, iters = 0, 0
    while max_iters is None or iters < max_iters:
        base = inbox.stat().st_mtime
        b = pickup_bundle(str(inbox), move_to=str(received))
        if b is not None:
            callback(b)
            n += 1
        else:
            _await_change(str(inbox), poll_interval, since=base)
        iters += 1
    return n

def drop_prompt(dir:str, # parent dead-drop directory
                 session_id:str, # which session's inbox to drop into
                 files:dict # {filename: content}, content str or bytes -- see drop_bundle
                 ) -> str: # the generated prompt_id (the bundle's directory name)
    "Drop a multi-file prompt bundle into a session's inbox/ (see drop_bundle). Returns the prompt_id, needed later to find the matching reply in outbox/ (see await_reply)."
    session_dir = Path(_resolve_safe(dir)) / session_id
    path = drop_bundle(str(session_dir / 'inbox'), files)
    return Path(path).name

def reply_bundle(dir:str, # parent dead-drop directory
                  session_id:str, # which session's outbox to drop into
                  prompt_id:str, # the id of the prompt being answered -- reused as the reply bundle's own name so the two sides match up
                  files:dict # {filename: content}, content str or bytes -- see drop_bundle
                  ) -> str: # path to the reply bundle directory
    "Drop a response bundle into a session's outbox/, reusing the prompt's own prompt_id as the bundle's directory name (see drop_bundle's bundle_id). Call this with the same id a watch_session() callback received as bundle['id']."
    session_dir = Path(_resolve_safe(dir)) / session_id
    return drop_bundle(str(session_dir / 'outbox'), files, bundle_id=prompt_id)

def await_reply(dir:str, # parent dead-drop directory
                 session_id:str, # which session's outbox to wait on
                 prompt_id:str, # the id returned by drop_prompt
                 poll_interval:float=1.0 # seconds between mtime checks while waiting
                 ) -> dict: # {'id':..., 'path':..., 'files':...} -- see read_bundle
    "Block until a same-id reply bundle appears in a session's outbox/ (see reply_bundle) -- the bundle directory only appears once fully written (drop_bundle's atomic rename), so there's no risk of reading a partial reply -- then read and return it."
    outbox_dir = Path(_resolve_safe(dir)) / session_id / 'outbox' / prompt_id
    # since=0.0: we only care that outbox_dir gets *created* at all (_await_change's
    # exists-loop), not that it changes again afterward -- a rename-into-place directory
    # never gets touched a second time, so the default since=None (baseline = mtime at the
    # moment it's first seen to exist) would wait forever for a change that never comes.
    _await_change(str(outbox_dir), poll_interval, since=0.0)
    return {'id': prompt_id, 'path': str(outbox_dir), 'files': read_bundle(outbox_dir)}

def pending_replies(dir:str, # parent dead-drop directory
                     session_id:str=None # session to check; default auto-detects (see _session_id)
                     ) -> list: # sorted prompt ids seen (received) but not yet answered (in outbox)
    "List prompt ids that have been received (claimed via watch_session) but have no matching bundle in outbox/ yet -- the crash-recovery check: a prompt sitting here across a restart was missed mid-processing, not lost before pickup (those are still sitting unclaimed in inbox/, see list_sessions/pickup_bundle)."
    session_dir = Path(_resolve_safe(dir)) / (session_id or _session_id())
    def _names(sub):
        d = session_dir / sub
        return {p.name for p in d.iterdir() if p.is_dir()} if d.exists() else set()
    return sorted(_names('received') - _names('outbox'))

def complete_reply(dir:str, # parent dead-drop directory
                    session_id:str, # which session's outbox/completed to use
                    prompt_id:str # the id of the reply being marked done -- same id as the original prompt
                    ) -> str: # path to the bundle's new location under completed/
    "Move a reply bundle from outbox/ to completed/ (atomic rename, same name) -- the producer's counterpart to watch_session()'s inbox -> received move. Whatever is doing the prompting calls this once it's actually consumed a reply (see await_reply), so outbox/ only ever holds replies still awaiting consumption (see unprocessed_replies)."
    session_dir = Path(_resolve_safe(dir)) / session_id
    completed_dir = session_dir / 'completed'
    completed_dir.mkdir(parents=True, exist_ok=True)
    dest = completed_dir / prompt_id
    (session_dir / 'outbox' / prompt_id).rename(dest)
    return str(dest)

def unprocessed_replies(dir:str, # parent dead-drop directory
                         session_id:str=None # session to check; default auto-detects (see _session_id)
                         ) -> list: # sorted prompt ids answered (in outbox) but not yet consumed (in completed)
    "List prompt ids whose reply is sitting in outbox/ but hasn't been moved to completed/ yet (see complete_reply) -- i.e. answered but not yet consumed by whatever's doing the prompting. The producer-side counterpart to pending_replies (which is the watcher-side 'claimed but not yet answered' check)."
    session_dir = Path(_resolve_safe(dir)) / (session_id or _session_id())
    def _names(sub):
        d = session_dir / sub
        return {p.name for p in d.iterdir() if p.is_dir()} if d.exists() else set()
    return sorted(_names('outbox') - _names('completed'))

# %% ../nbs/05_dead_drop.ipynb #22dadc91
def _last_complete_block(path:Path, marker:'re.Pattern'):
    "Scan `path` for lines matching `marker`; return (marker_count, text_of_last_complete_block_or_None) -- the block is everything strictly between the second-to-last and last marker line."
    if not path.exists(): return 0, None
    lines = path.read_text().splitlines()
    idxs = [i for i, l in enumerate(lines) if marker.search(l)]
    if not idxs: return 0, None
    prev = idxs[-2] if len(idxs) >= 2 else -1
    block = '\n'.join(lines[prev + 1:idxs[-1]]).strip()
    return len(idxs), (block or None)

# %% ../nbs/05_dead_drop.ipynb #d6c81894
def next_prompt(path:str, # path to a growing, marker-delimited prompt log (e.g. a file a human edits in Jupyter/an editor and appends a SEND line to when done typing)
                poll_interval:float=1.0, # seconds between mtime checks
                marker:str=r'^\s*-+\s*send\s*-+\s*$' # case-insensitive regex marking the end of a submitted block; a dash-padded SEND line by default
                ) -> str:
    "Block until `path` gains a new complete marker-delimited block, then return that block's text -- the newest multi-line message the other side submitted. Waits for the file to actually change (see _await_change), then re-checks the marker count, so an unrelated resave or a still-typing autosave doesn't false-trigger. Remembers how many markers it's already consumed in a sidecar state file (`{path}.dd_state`), so repeated calls -- e.g. one per turn of a conversation loop -- never re-fire on old content."
    path_ = Path(_resolve_safe(path))
    marker_re = re.compile(marker, re.IGNORECASE)
    state_file = path_.parent / (path_.name + '.dd_state')
    seen = int(state_file.read_text()) if state_file.exists() else _last_complete_block(path_, marker_re)[0]
    while True:
        base = path_.stat().st_mtime if path_.exists() else 0.0  # captured before the marker re-check, closing the same race watch() closes
        _await_change(str(path_), poll_interval, since=base)
        n, block = _last_complete_block(path_, marker_re)
        if n > seen:
            seen = n
            state_file.write_text(str(n))
            if block: return block
        # else: file changed but no new complete block yet (still typing, or an unrelated resave) -- keep waiting

# %% ../nbs/05_dead_drop.ipynb #3500579a
from contextlib import contextmanager

class StreamWriter:
    "Handle yielded by stream() -- call .write(chunk) for each piece of text as it's produced."
    def __init__(self, fh): self._fh = fh
    def write(self, chunk:str) -> None:
        "Append `chunk` to the drop, flushed immediately so a `tail -f` sees it live."
        self._fh.write(chunk)
        self._fh.flush()

@contextmanager
def stream(dir:str, # directory to drop into (created if it doesn't exist)
           name:str # filename to write -- same as a plain drop(name=...)
           ):
    "Context manager for writing a dead drop incrementally. Inside the `with` block, call the yielded StreamWriter's .write(chunk) for each piece of text as it's produced; each call appends straight to `dir/name` and flushes, so a concurrent `tail -f` sees it live."
    dir_ = Path(_resolve_safe(dir))
    dir_.mkdir(parents=True, exist_ok=True)
    with open(dir_ / name, 'w') as fh:
        yield StreamWriter(fh)
