"""Async file-based IPC: one side `drop()`s a file, another side -- possibly a different process, possibly a different machine reachable only via a synced/shared directory (Dropbox, rsync, an NFS mount, ...) -- `pickup()`s it later, no direct connection between the two required. Named after the spy tradecraft term. This is the "agent-loop file relay" deferred out of `02_remote.ipynb`'s original scope, now built out on its own -- and it subsumes an earlier hand-rolled prototype (`cycle.sh`/`watch.sh`, a bash-only prompt/response relay used to drive a Claude Code session from a Jupyter cell on a different machine) whose good ideas are generalized here: Maildir's atomic-rename trick (`drop()`/`pickup()`), and blocking-wait-on-mtime-change (`watch()`, `next_prompt()`) -- reimplemented in Python rather than shelled out to `stat`, because bash's 1-second mtime resolution left a real race between "checked, nothing pending" and "started waiting for the next change" (found the hard way: a drop landing in that gap could be missed forever).

Docs: https://drscotthawley.github.io/slmn/dead_drop.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_dead_drop.ipynb.

# %% auto #0
__all__ = ['DONE_MARKER', 'drop', 'pickup', 'watch', 'list_sessions', 'drop_bundle', 'read_bundle', 'drop_prompt', 'next_prompt',
           'StreamWriter', 'stream', 'reply_stream', 'await_prompt', 'pending_prompts', 'read_prompt', 'follow_file',
           'follow_reply']

# %% ../nbs/05_dead_drop.ipynb #2d949541
import re, time, uuid, os
from pathlib import Path
from .nbtools import _resolve_safe

# %% ../nbs/05_dead_drop.ipynb #9a1f3c02
_SESSION_ID = None  # per-process fallback, generated at most once

def _session_id() -> str:
    "Resolve the current session id: the `CLAUDE_CODE_SESSION_ID` env var if set, else a random id generated once and cached for the life of this process (so repeated calls in the same process reuse the same dead-drop subdirectory)."
    global _SESSION_ID
    env_id = os.environ.get('CLAUDE_CODE_SESSION_ID')
    if env_id: return env_id
    if _SESSION_ID is None:
        _SESSION_ID = uuid.uuid4().hex[:12]
    return _SESSION_ID

# %% ../nbs/05_dead_drop.ipynb #f81b6a3e
import platform, subprocess

def _os_info() -> str:
    "One-line OS description. On Linux this reads /etc/os-release for the distro name (e.g. 'Ubuntu 22.04.4 LTS') -- WSL2 runs a real Linux kernel, so this naturally reports the Linux distro rather than the Windows host, which is what actually matters here. On macOS, reports 'macOS <version>'. Falls back to platform.system() otherwise."
    system = platform.system()
    if system == 'Darwin':
        return f"macOS {platform.mac_ver()[0]}"
    if system == 'Linux':
        os_release = Path('/etc/os-release')
        if os_release.exists():
            info = dict(l.split('=', 1) for l in os_release.read_text().splitlines() if '=' in l)
            pretty = info.get('PRETTY_NAME', '').strip('"')
            if pretty: return pretty
        return 'Linux'
    return system

def _gpu_info() -> tuple:
    "GPU name(s) and total VRAM (in GB, one decimal place) via nvidia-smi, as two semicolon-joined strings, parallel across multiple GPUs -- ('none detected', 'none detected') if nvidia-smi isn't available or reports nothing."
    which = subprocess.run(['which', 'nvidia-smi'], capture_output=True, text=True).stdout.strip()
    if not which: return "none detected", "none detected"
    r = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total', '--format=csv,noheader,nounits'],
                        capture_output=True, text=True)
    rows = [l.strip() for l in r.stdout.strip().splitlines() if l.strip()]
    if r.returncode != 0 or not rows: return "none detected", "none detected"
    names, vrams = [], []
    for row in rows:
        name, mib = (p.strip() for p in row.rsplit(',', 1))
        names.append(name)
        vrams.append(f"{round(float(mib) / 1024, 1)} GB")
    return "; ".join(names), "; ".join(vrams)

def _machine_info_md() -> str:
    "Compose the MACHINE_INFO.md contents describing this machine: hostname, OS, CPU count, total RAM, GPU name(s), and VRAM (see _os_info, _gpu_info)."
    try:
        ram_gb = round(os.sysconf('SC_PAGE_SIZE') * os.sysconf('SC_PHYS_PAGES') / (1024 ** 3), 1)
        ram = f"{ram_gb} GB"
    except (ValueError, OSError):
        ram = "unknown"
    gpu_name, gpu_vram = _gpu_info()
    return (
        "# Machine Info\n\n"
        f"- Hostname: {platform.node()}\n"
        f"- OS: {_os_info()}\n"
        f"- CPUs: {os.cpu_count()}\n"
        f"- RAM: {ram}\n"
        f"- GPU: {gpu_name}\n"
        f"- VRAM: {gpu_vram}\n"
    )

def _write_machine_info(parent_dir:Path) -> None:
    "Write MACHINE_INFO.md into parent_dir if it doesn't already exist (first watch()er on this machine wins; later ones leave it alone)."
    path = parent_dir / "MACHINE_INFO.md"
    if not path.exists():
        path.write_text(_machine_info_md())

# %% ../nbs/05_dead_drop.ipynb #837e642b
def drop(dir:str, # directory to drop into (created if it doesn't exist)
         content:str, # the drop's body
         name:str=None # filename to use; default is a sortable `{timestamp}-{uuid8}` so pickups see drops in creation order
         ) -> str:
    "Atomically write a dead drop into `dir`, for another process -- possibly on another machine, via a synced/shared directory -- to `pickup()` or `watch()` later. Writes to a temp file in the same directory first, then atomically renames it into place (Maildir's trick), so a concurrent pickup/watch never sees a half-written drop. Returns the dropped file's final path."
    dir_ = Path(_resolve_safe(dir))
    dir_.mkdir(parents=True, exist_ok=True)
    fname = name or f"{time.time_ns()}-{uuid.uuid4().hex[:8]}"
    tmp = dir_ / f".tmp-{uuid.uuid4().hex}"
    tmp.write_text(content)
    final = dir_ / fname
    tmp.rename(final)
    return str(final)

# %% ../nbs/05_dead_drop.ipynb #e7916b04
def pickup(dir:str, # directory to check for drops
           delete:bool=True # remove the file after reading it, so each drop is picked up exactly once
           ) -> dict: # {'path':..., 'name':..., 'content':...}, or None if nothing's pending
    "Look for the oldest pending drop in `dir` (sorted by filename, so default drop() names -- timestamp-prefixed -- come out in creation order) and read it. Returns None if `dir` doesn't exist or has no drops. Ignores hidden files -- both its own in-progress temp files (`.tmp-*`) and stray dotfiles from other processes sharing the directory (e.g. an editor's `.foo.swp` if something's being edited in place there)."
    dir_ = Path(_resolve_safe(dir))
    if not dir_.exists(): return None
    candidates = sorted(f for f in dir_.iterdir() if f.is_file() and not f.name.startswith('.'))
    if not candidates: return None
    f = candidates[0]
    content = f.read_text()
    if delete: f.unlink()
    return {'path': str(f), 'name': f.name, 'content': content}

# %% ../nbs/05_dead_drop.ipynb #42a95f92
def _await_change(path:str, # file or directory to watch
                  poll_interval:float, # seconds between mtime checks
                  since:float=None # baseline mtime to compare against; if the path is already newer than this, returns immediately (closes the check-then-wait race -- pass the mtime you observed *before* you checked for existing content, not after)
                  ) -> None:
    "Block until `path`'s mtime is newer than `since` (default: newer than its mtime at call time). Waits for `path` to exist first if it doesn't yet."
    path_ = Path(path)
    while not path_.exists():
        time.sleep(poll_interval)
    base = since if since is not None else path_.stat().st_mtime
    while path_.stat().st_mtime <= base:
        time.sleep(poll_interval)

# %% ../nbs/05_dead_drop.ipynb #55f3628d
def watch(dir:str, # parent directory for drops; a session-scoped subdirectory is created (or reused) under it -- see module docs
          callback:callable, # called as callback(drop) for each drop, where drop is the dict pickup() returns
          poll_interval:float=1.0, # seconds between mtime checks while dir is empty
          delete:bool=True, # remove each drop after callback returns (passed through to pickup)
          max_iters:int=None, # stop after this many drops-or-idle-checks (mainly for tests/scripted runs -- omit to run forever)
          session_id:str=None # session id whose subdirectory to watch; default auto-detects (see _session_id)
          ) -> int:
    "Blocking loop: repeatedly pickup() drops from a session-scoped subdirectory of `dir` and pass each to `callback`; when that subdirectory is empty, blocks on its mtime change (see _await_change) instead of busy-polling pickup() itself. The subdirectory is named after `session_id` (or the auto-detected current session id if omitted), created if it doesn't exist yet or reused as-is if it does -- so multiple agents watching the same parent `dir` don't see each other's drops. Also writes MACHINE_INFO.md into `dir` itself the first time any session watches there (see _write_machine_info) -- a no-op on later calls once it exists. Runs forever unless `max_iters` is given -- stop it with Ctrl-C otherwise. Like slmn's other blocking primitives, this is CLI/import-only, never exposed over MCP, since it never returns promptly. Returns the number of drops processed."
    parent_ = Path(_resolve_safe(dir))
    parent_.mkdir(parents=True, exist_ok=True)
    _write_machine_info(parent_)
    dir_ = parent_ / (session_id or _session_id())
    dir_.mkdir(parents=True, exist_ok=True)
    n, iters = 0, 0
    while max_iters is None or iters < max_iters:
        base = dir_.stat().st_mtime  # captured before pickup(), so a drop landing right here is still caught below
        d = pickup(str(dir_), delete=delete)
        if d is not None:
            callback(d)
            n += 1
        else:
            _await_change(str(dir_), poll_interval, since=base)
        iters += 1
    return n

# %% ../nbs/05_dead_drop.ipynb #c2e4a9d7
def list_sessions(dir:str, # parent dead-drop directory (the same `dir` passed to watch())
                  require:tuple=None # if given, only count a subdirectory as a session when it contains at least one of these subdirectories, e.g. ('inbox','outbox')
                  ) -> list: # sorted list of session-id subdirectory names; [] if `dir` doesn't exist
    "List the session ids currently present as subdirectories of `dir` -- i.e. sessions that have called watch(dir, ...) here at least once -- so a producer can pick one to drop() into. Sorted alphabetically. Ignores hidden/dotted entries and non-directories. `require` exists because 'every subdirectory' is too loose once a dead-drop root holds anything else: the single-file workflow keeps its own prompts/ and responses/ directories right there, and those would otherwise be offered as sessions you could address but never get an answer from. Passing require=('inbox','outbox') restricts the result to directories actually set up for the prompt/reply exchange."
    dir_ = Path(_resolve_safe(dir))
    if not dir_.exists(): return []
    names = sorted(p.name for p in dir_.iterdir() if p.is_dir() and not p.name.startswith('.'))
    if not require: return names
    return [n for n in names if any((dir_/n/sub).is_dir() for sub in require)]


# %% ../nbs/05_dead_drop.ipynb #e5c1a7d3
def _prompt_id(text:str="" # representative text to derive the human-readable slug from (e.g. the prompt itself); safe to omit
                ) -> str:
    "Generate a bundle id: `{timestamp}-{slug}-{rand}`. The timestamp leads so bundle directories still sort chronologically (same reasoning as drop()'s default filename); `slug` is the first 6 lowercase alnum characters that survive stripping everything else out of `text` (falls back to 'prompt' if nothing survives, e.g. text that's empty or all-emoji) for a human-skimmable `ls`; `rand` is a short hex suffix (uuid4, same convention as drop()'s default filename) disambiguating same-second collisions."
    ts = time.strftime('%Y%m%dT%H%M%S')
    slug = re.sub(r'[^a-z0-9]', '', text.lower())[:6] or 'prompt'
    rand = uuid.uuid4().hex[:6]
    return f"{ts}-{slug}-{rand}"


# %% ../nbs/05_dead_drop.ipynb #f6d2b8e4
def drop_bundle(dir:str, # directory to drop the bundle into (created if it doesn't exist)
                 files:dict, # {filename: content}, content str or bytes
                 bundle_id:str=None # bundle directory name; auto-generated (see _prompt_id) from the first str-valued file's content if omitted
                 ) -> str: # path to the bundle directory
    "Atomically drop a multi-file bundle -- e.g. a prompt's text plus an image attachment -- as a single directory under `dir`. Writes every file into a hidden temp directory first, then atomically renames the whole directory into place (extends drop()'s Maildir trick to a whole bundle), so a concurrent pickup/watch never sees a partially-written bundle. Returns the bundle's final directory path."
    dir_ = Path(_resolve_safe(dir))
    dir_.mkdir(parents=True, exist_ok=True)
    if bundle_id is None:
        text = next((v for v in files.values() if isinstance(v, str)), "")
        bundle_id = _prompt_id(text)
    tmp = dir_ / f".tmp-{uuid.uuid4().hex}"
    tmp.mkdir()
    for fname, content in files.items():
        if isinstance(content, bytes): (tmp / fname).write_bytes(content)
        else: (tmp / fname).write_text(content)
    final = dir_ / bundle_id
    tmp.rename(final)
    return str(final)

def read_bundle(path:str # a bundle directory, as written by drop_bundle
                 ) -> dict: # {filename: content}, text decoded where possible, else raw bytes
    "Read every file in a bundle directory into {filename: content}, decoding as text where possible and falling back to raw bytes for anything that isn't (e.g. an image attachment)."
    dir_ = Path(path)
    files = {}
    for f in sorted(dir_.iterdir()):
        if not f.is_file() or f.name.startswith('.'): continue
        try: files[f.name] = f.read_text()
        except UnicodeDecodeError: files[f.name] = f.read_bytes()
    return files



# %% ../nbs/05_dead_drop.ipynb #a9c3e7f5
def drop_prompt(dir:str, # parent dead-drop directory
                 session_id:str, # which session's inbox to drop into
                 files:dict # {filename: content}, content str or bytes -- see drop_bundle
                 ) -> str: # the generated prompt_id (the bundle's directory name)
    "Drop a multi-file prompt bundle into a session's inbox/ (see drop_bundle). Returns the prompt_id, which names the reply file to watch for in outbox/ (see follow_reply). The prompt is a bundle -- a directory renamed into place in one step -- because the producer has the whole thing at once and it may carry attachments; the reply deliberately isn't (see reply_stream)."
    session_dir = Path(_resolve_safe(dir)) / session_id
    path = drop_bundle(str(session_dir / 'inbox'), files)
    return Path(path).name


# %% ../nbs/05_dead_drop.ipynb #22dadc91
def _last_complete_block(path:Path, marker:'re.Pattern'):
    "Scan `path` for lines matching `marker`; return (marker_count, text_of_last_complete_block_or_None) -- the block is everything strictly between the second-to-last and last marker line."
    if not path.exists(): return 0, None
    lines = path.read_text().splitlines()
    idxs = [i for i, l in enumerate(lines) if marker.search(l)]
    if not idxs: return 0, None
    prev = idxs[-2] if len(idxs) >= 2 else -1
    block = '\n'.join(lines[prev + 1:idxs[-1]]).strip()
    return len(idxs), (block or None)

# %% ../nbs/05_dead_drop.ipynb #d6c81894
def next_prompt(path:str, # path to a growing, marker-delimited prompt log (e.g. a file a human edits in Jupyter/an editor and appends a SEND line to when done typing)
                poll_interval:float=1.0, # seconds between mtime checks
                marker:str=r'^\s*-+\s*send\s*-+\s*$' # case-insensitive regex marking the end of a submitted block; a dash-padded SEND line by default
                ) -> str:
    "Block until `path` gains a new complete marker-delimited block, then return that block's text -- the newest multi-line message the other side submitted. Waits for the file to actually change (see _await_change), then re-checks the marker count, so an unrelated resave or a still-typing autosave doesn't false-trigger. Remembers how many markers it's already consumed in a sidecar state file (`{path}.dd_state`), so repeated calls -- e.g. one per turn of a conversation loop -- never re-fire on old content."
    path_ = Path(_resolve_safe(path))
    marker_re = re.compile(marker, re.IGNORECASE)
    state_file = path_.parent / (path_.name + '.dd_state')
    seen = int(state_file.read_text()) if state_file.exists() else _last_complete_block(path_, marker_re)[0]
    while True:
        base = path_.stat().st_mtime if path_.exists() else 0.0  # captured before the marker re-check, closing the same race watch() closes
        _await_change(str(path_), poll_interval, since=base)
        n, block = _last_complete_block(path_, marker_re)
        if n > seen:
            seen = n
            state_file.write_text(str(n))
            if block: return block
        # else: file changed but no new complete block yet (still typing, or an unrelated resave) -- keep waiting

# %% ../nbs/05_dead_drop.ipynb #3500579a
from contextlib import contextmanager

class StreamWriter:
    "Handle yielded by stream() -- call .write(chunk) for each piece of text as it's produced."
    def __init__(self, fh): self._fh = fh
    def write(self, chunk:str) -> None:
        "Append `chunk` to the drop, flushed immediately so a `tail -f` sees it live."
        self._fh.write(chunk)
        self._fh.flush()

@contextmanager
def stream(dir:str, # directory to drop into (created if it doesn't exist)
           name:str # filename to write -- same as a plain drop(name=...)
           ):
    "Context manager for writing a dead drop incrementally. Inside the `with` block, call the yielded StreamWriter's .write(chunk) for each piece of text as it's produced; each call appends straight to `dir/name` and flushes, so a concurrent `tail -f` sees it live."
    dir_ = Path(_resolve_safe(dir))
    dir_.mkdir(parents=True, exist_ok=True)
    with open(dir_ / name, 'w') as fh:
        yield StreamWriter(fh)

DONE_MARKER = '---DONE---'  # terminates a streamed reply; see reply_stream

@contextmanager
def reply_stream(dir:str, # parent dead-drop directory
                 session_id:str, # the session being answered -- its outbox/ is written to
                 prompt_id:str, # the id of the prompt being answered (as returned by drop_prompt / seen on an inbox bundle)
                 name:str=None # reply filename within outbox/; defaults to '{prompt_id}.md'
                 ):
    "The responder's half of a session exchange: stream a reply into `session_id`'s outbox/, answering `prompt_id`. The counterpart to drop_prompt() on the producer side. A reply is a plain appended-to file rather than an atomically-renamed bundle *because* it has to be readable while it's still being written -- a bundle only becomes visible once complete, which is right for a prompt (written all at once) and useless for a reply someone is watching arrive. DONE_MARKER is appended when the `with` block exits normally, and deliberately NOT when it exits via an exception: a reply file that stops growing without its terminator is therefore distinguishable from a finished one, which is the whole reason completion is marked in-band instead of inferred from the file merely existing."
    outbox = Path(_resolve_safe(dir)) / session_id / 'outbox'
    with stream(str(outbox), name or f'{prompt_id}.md') as w:
        yield w
        w.write(f'\n{DONE_MARKER}\n')

def await_prompt(dir:str, # parent dead-drop directory
                 session_id:str=None, # session to serve; default auto-detects (see _session_id)
                 poll_interval:float=1.0 # seconds between checks while the inbox is quiet
                 ) -> dict: # {'id':..., 'files':...} -- the oldest unanswered prompt
    "Block until this session has an unanswered prompt, then return the oldest one -- the responder's entry point, answering a producer's drop_prompt(). Returns straight away if one is already waiting. Creates the session's inbox/ and outbox/ first (and MACHINE_INFO.md alongside, if absent -- same as watch()): waiting for prompts is exactly what announces a session, since until those two directories exist list_sessions(require=('inbox','outbox')) can't see it and a producer has nowhere to address a prompt. The prompt itself stays in inbox/ (see read_prompt); what stops it counting as outstanding is a reply file appearing in outbox/, which reply_stream() creates the moment it starts writing -- so an answer already in progress won't be handed out twice. Idles on the inbox's mtime rather than re-listing on a timer, with the baseline captured *before* the check, so a prompt landing in that gap is caught on the next pass instead of waiting out a full interval (the same race watch() closes)."
    parent = Path(_resolve_safe(dir))
    parent.mkdir(parents=True, exist_ok=True)
    _write_machine_info(parent)
    session_dir = parent / (session_id or _session_id())
    inbox = session_dir / 'inbox'
    for sub in (inbox, session_dir / 'outbox'): sub.mkdir(parents=True, exist_ok=True)
    while True:
        base = inbox.stat().st_mtime if inbox.exists() else 0.0
        ids = pending_prompts(dir, session_id)
        if ids: return {'id': ids[0], 'files': read_prompt(dir, session_id or _session_id(), ids[0])}
        _await_change(str(inbox), poll_interval, since=base)

def pending_prompts(dir:str, # parent dead-drop directory
                    session_id:str=None # session to check; default auto-detects (see _session_id)
                    ) -> list: # sorted prompt ids in inbox/ with no reply in outbox/
    "The prompt ids sitting in a session's inbox/ that have no reply in its outbox/ yet -- i.e. the work still to do. This is the two-directory protocol's entire bookkeeping: nothing is ever moved, renamed or deleted, so 'what's outstanding' is a set difference computed on demand instead of state that has to be maintained correctly across directories (and can therefore drift out of sync, or be left wrong by a crash at the wrong instant). Both halves of an exchange stay where they were written, which also makes the directories their own permanent record. Note this reports *unanswered*, not *unfinished*: a reply file counts the moment it's created, even mid-stream, so use this to find work to pick up -- to judge whether a reply actually completed, check for DONE_MARKER (see follow_file)."
    session_dir = Path(_resolve_safe(dir)) / (session_id or _session_id())
    inbox, outbox = session_dir/'inbox', session_dir/'outbox'
    have = {p.name for p in inbox.iterdir() if p.is_dir() and not p.name.startswith('.')} if inbox.exists() else set()
    done = {p.stem for p in outbox.iterdir() if p.is_file() and not p.name.startswith('.')} if outbox.exists() else set()
    return sorted(have - done)

def read_prompt(dir:str, # parent dead-drop directory
                session_id:str, # session whose inbox/ holds the prompt
                prompt_id:str # the bundle id, e.g. from pending_prompts
                ) -> dict: # {filename: content} -- see read_bundle
    "Read a prompt bundle out of a session's inbox/ *without* claiming, moving or deleting it -- the bundle counterpart to pickup(), minus the consuming. A prompt is answered by writing to outbox/, never by being taken; leaving it in place is what lets pending_prompts() work as a plain set difference, and keeps the whole exchange readable after the fact."
    return read_bundle(Path(_resolve_safe(dir)) / session_id / 'inbox' / prompt_id)

def follow_file(path:str, # file to follow; it doesn't have to exist yet
                poll_interval:float=1.0 # seconds between checks
                ):  # generator of str chunks -- each newly-appended stretch of text, DONE_MARKER excluded
    "Follow a file being streamed into by a writer (see stream/reply_stream), yielding each newly-appended stretch of text as it lands -- `tail -f` as a generator. Returns once the content ends with DONE_MARKER, which is stripped and never yielded, so joining everything yielded gives exactly the reply. Waits for `path` to appear rather than requiring it upfront, since the reader normally starts before the responder has written anything. Polls instead of using inotify deliberately: the whole point of dead_drop is that the directory can be a synced/networked one, where filesystem change events don't cross the boundary but mtime and size still do."
    seen = 0
    while True:
        if Path(path).exists():
            text = Path(path).read_text()
            stripped = text.rstrip()
            if stripped.endswith(DONE_MARKER):
                content = stripped[:-len(DONE_MARKER)].rstrip()
                if len(content) > seen: yield content[seen:]
                return
            if len(text) > seen:
                yield text[seen:]
                seen = len(text)
        time.sleep(poll_interval)

def follow_reply(dir:str, # parent dead-drop directory
                 session_id:str, # the session that was prompted
                 prompt_id:str, # the id returned by drop_prompt
                 poll_interval:float=1.0, # seconds between checks
                 name:str=None # reply filename within outbox/; defaults to '{prompt_id}.md' (matches reply_stream)
                 ):  # generator of str chunks -- see follow_file
    "Follow the streamed reply to `prompt_id` as the responder writes it (see follow_file) -- the producer-side counterpart to reply_stream(), and the last step of an exchange: drop_prompt() to send, follow_reply() to receive. Returns when the reply is terminated by DONE_MARKER; a caller that doesn't care about seeing it arrive can simply join everything yielded."
    outbox = Path(_resolve_safe(dir)) / session_id / 'outbox'
    yield from follow_file(str(outbox / (name or f'{prompt_id}.md')), poll_interval)
