"""An *optional* MCP server exposing the same tools as the `slmn` CLI, for any MCP-speaking client (Claude Code/Desktop, Cursor, Codex, ...). Nothing here is required to use the tools -- import them directly from `slmn.nbtools`/`slmn.misc`, or drive them via the `slmn` CLI. This is just one more door in.

Docs: https://drscotthawley.github.io/slmn/mcp.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_mcp.ipynb.

# %% auto #0
__all__ = ['mcp', 'main']

# %% ../nbs/03_mcp.ipynb #4ae468e2
try:
    from fastmcp import FastMCP
except ImportError as e:
    raise ImportError(
        "The MCP server needs the 'mcp' extra: pip install slmn[mcp] (or 'uv pip install slmn[mcp]'). "
        "It's optional -- slmn.nbtools/slmn.misc/slmn.remote and the `slmn` CLI work without it."
    ) from e
from .nbtools import read_nb, grep_nb, edit_nb, patch_nb_cell, insert_cells, add_nb_cell, write_nb_docs, write_project_docs
from .misc import read_pdf, gpu_free
from .remote import remote_launch, remote_status, remote_smoke_test, remote_gpu_free, fetch_url, check_ci
from .publish import publish

# %% ../nbs/03_mcp.ipynb #ce6a9a7e
mcp = FastMCP("slmn")
for _fn in (read_nb, grep_nb, edit_nb, patch_nb_cell, insert_cells, add_nb_cell, write_nb_docs, write_project_docs, read_pdf, gpu_free,
            remote_launch, remote_status, remote_smoke_test, remote_gpu_free, fetch_url, check_ci, publish):
    mcp.add_tool(_fn)

# %% ../nbs/03_mcp.ipynb #080f6962
def main():
    "Entry point for the `slmn-mcp` console script -- runs the server over stdio, the transport MCP clients spawn locally."
    mcp.run()
