"""Sundry utilities that don't fit a bigger category yet: reading PDFs and checking local GPU availability. (Web fetching, GitHub CI checks, and remote GPU orchestration live in `remote` -- they're all about reaching outside the local machine.)

Docs: https://drscotthawley.github.io/slmn/misc.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_misc.ipynb.

# %% auto #0
__all__ = ['read_pdf', 'gpu_free', 'install_skills']

# %% ../nbs/04_misc.ipynb #58e333a2
import subprocess, os, shutil
from pathlib import Path
import pymupdf
from .nbtools import _resolve_safe

# %% ../nbs/04_misc.ipynb #2683b53e
def read_pdf(path:str, # path to the PDF file
             start_page:int, # first page to extract, 1-indexed
             end_page:int # last page to extract, inclusive
             ) -> str:
    "Extract plain text from a PDF file, by 1-indexed page range."
    path = _resolve_safe(path)
    doc = pymupdf.open(path)
    out = []
    for i in range(start_page - 1, min(end_page, len(doc))):
        out.append(f"\n--- Page {i+1} ---\n{doc[i].get_text()}")
    return ''.join(out)

# %% ../nbs/04_misc.ipynb #d8a4d075
def gpu_free(gpu_idx:int=0, # which GPU to check
             busy_threshold_mib:int=2000 # VRAM usage (MiB) below which the GPU still counts as free
             ) -> dict:
    "Check whether a local GPU is free for compute. Tries nvidia-smi first; falls back to checking /dev/nvidia* via fuser (works on some WSL setups); if neither is available, assumes free. Returns {'free': bool, 'detail': str}."
    nvidia_smi = subprocess.run(['which', 'nvidia-smi'], capture_output=True, text=True).stdout.strip()
    if nvidia_smi:
        r = subprocess.run(['nvidia-smi', '-i', str(gpu_idx), '--query-compute-apps=pid,used_gpu_memory,name',
                             '--format=csv,noheader'], capture_output=True, text=True)
        apps = r.stdout.strip()
        if not apps:
            return {'free': True, 'detail': f'GPU {gpu_idx}: FREE'}
        total_mib = 0
        procs = []
        for line in apps.splitlines():
            pid, mem, name = [x.strip() for x in line.split(',', 2)]
            mib = int(''.join(c for c in mem if c.isdigit()) or 0)
            total_mib += mib
            procs.append(f"PID {pid} | {mem} | {name}")
        if total_mib < busy_threshold_mib:
            return {'free': True, 'detail': f'GPU {gpu_idx}: FREE ({total_mib} MiB in use, below {busy_threshold_mib} MiB threshold)'}
        return {'free': False, 'detail': f'GPU {gpu_idx}: BUSY ({total_mib} MiB in use)\n  ' + '\n  '.join(procs)}

    if os.path.exists('/dev') and any(f.startswith('nvidia') for f in os.listdir('/dev')):
        r = subprocess.run(['fuser'] + [f'/dev/{f}' for f in os.listdir('/dev') if f.startswith('nvidia')],
                            capture_output=True, text=True)
        procs = r.stdout.split()
        if not procs:
            return {'free': True, 'detail': f'GPU {gpu_idx}: FREE (nvidia-smi unavailable; no /dev/nvidia* users)'}
        return {'free': False, 'detail': f'GPU {gpu_idx}: BUSY (nvidia-smi unavailable; /dev/nvidia* in use by PIDs: {" ".join(procs)})'}

    return {'free': True, 'detail': f'GPU {gpu_idx}: FREE (nvidia-smi unavailable; no GPU device files found; assuming free)'}

# %% ../nbs/04_misc.ipynb #fb0bd7ce
def install_skills(dest:str=None, # directory to install into; defaults to '.claude/skills' under the current dir (or '~/.claude/skills' when user=True)
                   user:bool=False, # install into the user-level '~/.claude/skills' instead of the current project's '.claude/skills'
                   force:bool=False # overwrite a skill that's already installed (default: skip it, so hand-edits to an installed skill aren't clobbered)
                   ) -> str:
    "Copy slmn's packaged Claude Code skills -- the slmn/skills/<name>/SKILL.md dirs shipped as package data -- into a `.claude/skills` directory so an agent (Claude Code, etc.) can discover them. Installs into the current project by default; pass user=True for the user-level dir, or an explicit `dest`. Each skill is copied as its own <name>/ subdir; existing ones are skipped unless force=True. Returns a short report of what was installed vs skipped."
    import slmn as _pkg
    src_root = Path(_pkg.__file__).parent / 'skills'
    if not src_root.exists():
        return f"No packaged skills found (looked in {src_root})."
    skills = sorted((d for d in src_root.iterdir() if (d / 'SKILL.md').exists()), key=lambda d: d.name)
    if not skills:
        return f"No skills to install in {src_root}."
    if dest is not None: base = Path(dest).expanduser()
    elif user: base = Path('~/.claude/skills').expanduser()
    else: base = Path('.claude/skills')
    base = Path(_resolve_safe(str(base)))
    base.mkdir(parents=True, exist_ok=True)
    installed, skipped = [], []
    for sd in skills:
        tgt = base / sd.name
        if tgt.exists() and not force:
            skipped.append(sd.name); continue
        if tgt.exists(): shutil.rmtree(tgt)
        shutil.copytree(sd, tgt)
        installed.append(sd.name)
    lines = [f"skills -> {base}"]
    if installed: lines.append(f"  installed: {', '.join(installed)}")
    if skipped: lines.append(f"  skipped (already present; force=True to overwrite): {', '.join(skipped)}")
    return '\n'.join(lines)
