"""Read, grep, and edit Jupyter notebook cells directly (by cell id), without hand-rolling JSON surgery each time. Plain functions -- import them directly, drive them from the `slmn` CLI, or expose them over MCP (see `03_mcp.ipynb`).

Docs: https://drscotthawley.github.io/slmn/nbtools.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_nbtools.ipynb.

# %% auto #0
__all__ = ['read_nb', 'grep_nb', 'edit_nb', 'patch_nb_cell', 'insert_cells', 'add_nb_cell', 'write_nb_docs', 'write_project_docs']

# %% ../nbs/01_nbtools.ipynb #52efb7a3
import json, re, os
from pathlib import Path
import nbformat as _nbf

# %% ../nbs/01_nbtools.ipynb #sandbox01
def _resolve_safe(path:str) -> str:
    "Resolve `path`, enforcing SLMN_SANDBOX_ROOTS if set (colon-separated allowed directories, e.g. '/home/user/notebooks:/tmp'). Off by default: with no env var, any path is allowed, same as before sandboxing existed. Raises PermissionError if the resolved path falls outside every allowed root. Every path-taking tool in this module calls this first."
    resolved = Path(path).resolve()
    roots = os.environ.get('SLMN_SANDBOX_ROOTS')
    if not roots: return str(resolved)
    allowed = [Path(r).resolve() for r in roots.split(':') if r]
    if not any(resolved.is_relative_to(root) for root in allowed):
        raise PermissionError(f"{path!r} resolves outside SLMN_SANDBOX_ROOTS ({roots})")
    return str(resolved)

# %% ../nbs/01_nbtools.ipynb #a960cad5
def read_nb(path:str, # path to the .ipynb file
            cell_ids:list[str]=None, # if given, only these cells' full source (ids may be partial/substring matches)
            full:bool=False # if True (and no cell_ids given), print full source of every cell
            ) -> str:
    "Read cell source(s) from a Jupyter notebook. With no cell_ids and full=False, lists every cell's id + a source preview (one line each) -- good for getting your bearings before a targeted read."
    path = _resolve_safe(path)
    nb = json.load(open(path))
    cell_ids = cell_ids or []
    out = []
    for cell in nb['cells']:
        cid = cell.get('id', '')
        src = ''.join(cell['source'])
        if full or (cell_ids and any(q in cid for q in cell_ids)):
            out.append(f"=== {cid} ===\n{src}\n")
        elif not cell_ids:
            out.append(f"{cid}  {src[:60].replace(chr(10), ' ')}")
    return '\n'.join(out)

# %% ../nbs/01_nbtools.ipynb #a3fda976
def grep_nb(path:str, # path to the .ipynb file
            pattern:str, # regex pattern to search for, per line, within each cell's source
            context:int=0, # lines of context before/after each match to include
            line_numbers:bool=False # prefix each shown line with its (0-based) line number within the cell
            ) -> str:
    "Grep cell sources in a Jupyter notebook. Returns the matching cells (id header + matching/context lines); empty string if nothing matched."
    path = _resolve_safe(path)
    nb = json.load(open(path))
    blocks = []
    for cell in nb['cells']:
        cid = cell.get('id', '')
        src = ''.join(cell.get('source', []))
        lines = src.split('\n')
        match_indices = [i for i, l in enumerate(lines) if re.search(pattern, l)]
        if not match_indices: continue
        shown = set()
        cell_lines = [f"=== {cid} ==="]
        for mi in match_indices:
            lo, hi = max(0, mi - context), min(len(lines) - 1, mi + context)
            if lo > 0 and shown and min(shown) > lo + 1:
                cell_lines.append('--')
            for li in range(lo, hi + 1):
                if li not in shown:
                    prefix = f"{li:4d}: " if line_numbers else ""
                    marker = ">" if li == mi else " "
                    cell_lines.append(f"{marker}{prefix}{lines[li]}")
                    shown.add(li)
        blocks.append('\n'.join(cell_lines))
    return '\n\n'.join(blocks)

# %% ../nbs/01_nbtools.ipynb #9e821d86
def edit_nb(path:str, # path to the .ipynb file
            cell_id:str, # cell id, or a prefix of one
            old_str:str, # text to find in the cell's source (first occurrence)
            new_str:str # replacement text
            ) -> str:
    "Replace the first occurrence of old_str with new_str in one cell's source, addressed by id-prefix. Falls back to a trailing-whitespace-insensitive match if the exact text isn't found. Raises ValueError if the cell or the text can't be found."
    path = _resolve_safe(path)
    nb = json.load(open(path))
    cell = next((c for c in nb['cells'] if c.get('id', '').startswith(cell_id)), None)
    if cell is None:
        raise ValueError(f"cell {cell_id!r} not found in {path}")
    src = ''.join(cell['source'])
    if old_str not in src:
        strip_trailing = lambda s: '\n'.join(l.rstrip() for l in s.split('\n'))
        src_stripped, old_stripped = strip_trailing(src), strip_trailing(old_str)
        if old_stripped not in src_stripped:
            raise ValueError(f"old_string not found in cell {cell_id}")
        src, old_str = src_stripped, old_stripped
    cell['source'] = src.replace(old_str, new_str, 1)
    json.dump(nb, open(path, 'w'), indent=1, ensure_ascii=False)
    return f"OK: updated cell {cell_id} in {path}"

# %% ../nbs/01_nbtools.ipynb #355ef52b
def patch_nb_cell(path:str, # path to the .ipynb file
                   cell_id:str, # exact cell id
                   new_source:str # the cell's complete new source, replacing the old source entirely
                   ) -> str:
    "Replace a cell's entire source (exact id match, not a prefix -- use this when you want to overwrite a cell wholesale rather than patch part of it; see edit_nb for a targeted string replacement). Raises ValueError if the cell isn't found."
    path = _resolve_safe(path)
    nb = json.load(open(path))
    cell = next((c for c in nb['cells'] if c.get('id') == cell_id), None)
    if cell is None:
        raise ValueError(f"cell {cell_id} not found in {path}")
    cell['source'] = new_source
    json.dump(nb, open(path, 'w'), indent=1, ensure_ascii=False)
    return f"OK: patched cell {cell_id} in {path}"

# %% ../nbs/01_nbtools.ipynb #4894c534
def insert_cells(path:str, # path to the .ipynb file
                  anchor_id:str, # exact cell id to insert after
                  sources:list[str], # one or more new cells' source, inserted in order right after the anchor -- plain source, no '#| ...' directives (see add_nb_cell)
                  export:bool=True, # forwarded to add_nb_cell for every inserted cell -- see there
                  eval:bool=True # forwarded to add_nb_cell for every inserted cell -- see there
                  ) -> str:
    "Insert one or more new code cells immediately after the cell with id `anchor_id`. A thin bulk convenience wrapper over add_nb_cell (the single-cell primitive), so the actual nbformat plumbing -- including the '#| export'/'#| eval: false' directive handling -- lives in one place. Raises ValueError if the anchor isn't found."
    last = anchor_id
    for s in sources:
        last = add_nb_cell(path, s, cell_type='code', after_id=last, export=export, eval=eval)
    return f"OK: inserted {len(sources)} cell(s) after {anchor_id} in {path}"

# %% ../nbs/01_nbtools.ipynb #57f27381
# Only these two directives are managed by add_nb_cell's export/eval flags; any other leading
# directive a caller includes (e.g. '#| default_exp', '#| hide', '#| echo: false') is preserved.
_MANAGED_DIRECTIVE_RE = re.compile(r'^[ \t]*#\|[ \t]*(?:export|eval:[ \t]*false)[ \t]*(?:\n|$)')

def _strip_managed_directives(source:str) -> str:
    "Remove leading '#| export' / '#| eval: false' lines (the two add_nb_cell regenerates from its flags), leaving every other line -- including other '#| ...' directives -- untouched."
    while _MANAGED_DIRECTIVE_RE.match(source):
        source = _MANAGED_DIRECTIVE_RE.sub('', source, count=1)
    return source

def add_nb_cell(path:str, # path to the .ipynb file
                source:str, # the new cell's source text. Don't include '#| export'/'#| eval: false' -- they're regenerated from the flags below (any you do include are stripped first, so it stays idempotent). OTHER directives like '#| default_exp' or '#| hide' ARE preserved, so pass those literally.
                cell_type:str='code', # nbformat cell type: 'code', 'markdown', or 'raw'
                after_id:str=None, # id of the cell to insert immediately after; None appends at the end (in cell order, NOT a raw file append)
                cell_id:str=None, # if given, force the new cell's id (e.g. to match an intended nbdev '# %%' marker); default lets nbformat assign one
                export:bool=True, # code cells only: prepend '#| export' so nbdev exports this cell into the module. Ignored for markdown/raw cells.
                eval:bool=True # code cells only: if False, prepend '#| eval: false' so nbdev skips executing this cell during tests/docs (e.g. a live-server/network demo). Ignored for markdown/raw cells.
                ) -> str:
    "Add a new cell to a Jupyter notebook and return its id. Appends to the end by default, or inserts right after `after_id`. `cell_type` is an nbformat type ('code'/'markdown'/'raw') -- note that boopiter-style note/prompt/assistant cells are all 'markdown' at the nbformat level. This tool -- not the caller -- owns the '#| export'/'#| eval: false' directives for code cells: pass plain source and use `export`/`eval` (any of those two you include literally get stripped and regenerated, so it's idempotent; other directives like '#| default_exp'/'#| hide' are left as-is). Reads/writes the file as plain JSON (indent=1) like the other nbtools here, so a one-cell add stays a one-cell git diff rather than reserializing the whole notebook. Raises ValueError on an unknown `cell_type`, or an `after_id` that isn't present."
    path = _resolve_safe(path)
    nb = json.load(open(path))
    makers = {'code': _nbf.v4.new_code_cell, 'markdown': _nbf.v4.new_markdown_cell, 'raw': _nbf.v4.new_raw_cell}
    if cell_type not in makers:
        raise ValueError(f"cell_type must be one of {sorted(makers)}, got {cell_type!r}")
    if cell_type == 'code':
        directives = [d for d, on in (('#| export', export), ('#| eval: false', not eval)) if on]
        source = '\n'.join(directives + [_strip_managed_directives(source)])
    cell = dict(makers[cell_type](source))  # nbformat builds a schema-valid cell (id/metadata/etc.); keep it as a plain dict
    if cell_id is not None: cell['id'] = cell_id
    cells = nb['cells']
    if after_id is None:
        cells.append(cell)
    else:
        idx = next((i for i, c in enumerate(cells) if c.get('id') == after_id), None)
        if idx is None:
            raise ValueError(f"after_id {after_id!r} not found in {path}")
        cells.insert(idx + 1, cell)
    json.dump(nb, open(path, 'w'), indent=1, ensure_ascii=False)
    return cell['id']

# %% ../nbs/01_nbtools.ipynb #1fbeff57
def write_nb_docs(path:str, # path to the .ipynb file
               notes:list=None, # markdown Note cells to INSERT: a list of [after_id, source] pairs. Each cell is inserted right after the cell whose id equals after_id; order within the list is preserved even when several notes share one anchor.
               patches:list=None, # existing cells to REWRITE: a list of [cell_id, new_source] pairs. Each named cell's entire source is replaced wholesale (like patch_nb_cell).
               cell_type:str='markdown' # nbformat cell type for the inserted `notes` ('markdown' for docs; 'code'/'raw' also accepted)
               ) -> str:
    "Apply a batch of documentation edits to a notebook in ONE atomic pass: insert markdown section-Note cells after named anchor cells (`notes`) and/or rewrite existing cells wholesale (`patches`). Every referenced id is validated against the notebook FIRST, so a single wrong id raises before anything is written -- no half-applied state (the failure mode of firing off many add_nb_cell/patch_nb_cell calls in a row, where one bad id leaves the earlier ones already committed). The whole notebook is written once with json.dump(indent=1), so it stays a minimal git diff. This is the reusable form of the 'add section headings throughout a notebook, then tidy the index' workflow -- point it at any nbdev notebook (slmn's own, or another project like boopiter) to document it. `notes` source is inserted verbatim (markdown needs no directives); for code cells that need '#| export'/'#| eval' use add_nb_cell instead."
    path = _resolve_safe(path)
    nb = json.load(open(path))
    notes = notes or []
    patches = patches or []
    makers = {'code': _nbf.v4.new_code_cell, 'markdown': _nbf.v4.new_markdown_cell, 'raw': _nbf.v4.new_raw_cell}
    if cell_type not in makers:
        raise ValueError(f"cell_type must be one of {sorted(makers)}, got {cell_type!r}")
    cells = nb['cells']
    # validate every id up front -- atomic: nothing is written unless all ids resolve
    ids = {c.get('id') for c in cells}
    missing = [a for a, _ in notes if a not in ids] + [cid for cid, _ in patches if cid not in ids]
    if missing:
        raise ValueError(f"cell id(s) not found in {path}: {missing}")
    # rewrites first -- id-addressed, so unaffected by the inserts below
    for cid, new_source in patches:
        next(c for c in cells if c.get('id') == cid)['source'] = new_source
    # then inserts; re-find the anchor each time and skip past notes already added after it,
    # so shifting indices don't matter and a group sharing one anchor keeps input order
    added = set()
    for after_id, src in notes:
        pos = next(i for i, c in enumerate(cells) if c.get('id') == after_id) + 1
        while pos < len(cells) and cells[pos].get('id') in added:
            pos += 1
        cell = dict(makers[cell_type](src))
        added.add(cell['id'])
        cells.insert(pos, cell)
    json.dump(nb, open(path, 'w'), indent=1, ensure_ascii=False)
    return f"OK: {path} -- inserted {len(notes)} note(s), patched {len(patches)} cell(s)"

# %% ../nbs/01_nbtools.ipynb #792a24f2
def write_project_docs(specs:dict, # {notebook_path: {'notes': [[after_id, source], ...], 'patches': [[cell_id, new_source], ...]}} -- one entry per notebook to touch; either key may be omitted or None
                        llms_txt:dict=None # optional {path: source} of extra plain-text files to write verbatim, e.g. {'nbs/llms.txt': '# proj\n> ...'} -- see the llms.txt section below
                        ) -> str:
    """Document a whole nbdev project in one call: apply a write_nb_docs batch to each notebook
    named in `specs`, plus optionally write extra plain-text files (llms_txt). Validates every
    cell id across every notebook FIRST, so a bad id in notebook #5 doesn't leave #1-4 already
    rewritten -- the project-wide version of write_nb_docs's own atomicity.

    This is the level to reach for when repeating slmn's own documentation pass (section-Note
    headings per notebook + a tidied index/README) on another nbdev project, e.g. boopiter.

    --- The llms.txt recipe (read this before using `llms_txt` for real) ---

    llms.txt (https://llmstxt.org) is a project-summary file for LLMs, analogous to
    robots.txt. Getting it live on an nbdev project's GitHub Pages site is NOT just "write the
    file" -- three build-config edits are needed too, and they're NOT notebook cells, so
    write_project_docs does not attempt them; do them by hand (or with plain file edits) once
    per project, then use `llms_txt` here just to (re)write nbs/llms.txt's content itself:

    1. pyproject.toml: add `pysym2md` and `llms-txt` (the pip package; ships the `llms_txt2ctx`
       command) to the `dev` extra -- NOT a new extra of their own. Both of nbdev's reusable
       GitHub Actions (nbdev3-ci for tests, quarto-ghp3 for the Pages deploy) hardcode
       `pip install -e ".[dev]"`, so anything the docs *build* needs must live in `dev`.

    2. nbs/_quarto.yml, under `project:`:
         pre-render:
           - pysym2md --output_file apilist.txt <pkg>      # <pkg> = the import name
         post-render:
           - llms_txt2ctx llms.txt --optional true --save_nbdev_fname llms-ctx-full.txt
           - llms_txt2ctx llms.txt --save_nbdev_fname llms-ctx.txt
         resources:
           - "*.txt"

    3. .gitignore: add `nbs/apilist.txt` and `nbs/llms-ctx*.txt` (regenerated every build; the
       `llms-ctx*.txt` actually land in nbdev's `_proc/` dir, which is normally already
       ignored -- add the nbs/ patterns anyway since apilist.txt lands next to llms.txt).

    4. nbs/llms.txt itself: H1 title, `>` blockquote summary, a detail paragraph or two, then
       `##`-headed link sections (`[name](url): description`) pointing at the site's published
       `*.html.md` doc pages, and an `## Optional` section linking `apilist.txt` (its content
       is included only when a context-builder asks for the fuller `llms-ctx-full.txt`).

    Gotchas learned building this for slmn (2026-07-20): `llms_txt2ctx` DOWNLOADS every linked
    URL and inlines it -- so links must point at the already-published site, not local files.
    On the very first deploy after wiring this up, `apilist.txt` isn't live yet, so that one
    build's `llms-ctx-full.txt` embeds GitHub's 404 page for the Optional-section link; it
    self-heals on the next deploy once apilist.txt exists. `llms-ctx.txt` (no --optional) is
    unaffected since it doesn't reference apilist.txt. `pysym2md <pkg>` pulls every symbol's
    signature and docstring straight from the installed package -- another reason to keep
    docstrings real (see write_nb_docs's own docstring for the matching per-notebook rule).
    """
    resolved = {}
    for path, spec in specs.items():
        p = _resolve_safe(path)
        nb = json.load(open(p))
        ids = {c.get('id') for c in nb['cells']}
        notes, patches = (spec.get('notes') or []), (spec.get('patches') or [])
        missing = [a for a, _ in notes if a not in ids] + [cid for cid, _ in patches if cid not in ids]
        if missing:
            raise ValueError(f"cell id(s) not found in {path}: {missing}")
        resolved[path] = spec
    out = [write_nb_docs(path, notes=spec.get('notes'), patches=spec.get('patches')) for path, spec in resolved.items()]
    for path, source in (llms_txt or {}).items():
        Path(_resolve_safe(path)).write_text(source)
        out.append(f"OK: wrote {path}")
    return '\n'.join(out)
