"""Automate the nbdev edit->ship loop over the git/gh CLIs: nbdev-clean/export, a reviewed commit, push, wait for CI, and (on a feature branch) open and merge a PR to main. One confirm gate doubles as an interactive prompt and an agent read-and-authorize handoff. Only the 'github' destination is wired up so far (pypi/conda later).

Docs: https://drscotthawley.github.io/slmn/publish.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_publish.ipynb.

# %% auto #0
__all__ = ['publish']

# %% ../nbs/06_publish.ipynb #9679b72f
import os, subprocess, sys, time
from pathlib import Path

# %% ../nbs/06_publish.ipynb #b870f5c9
def _run(cmd:list, cwd:str=None, capture:bool=True) -> subprocess.CompletedProcess:
    "Run `cmd` (an argv list, never a shell string -- no quoting/injection surface). `capture=False` lets it stream straight to the terminal (used for `gh run watch`, whose live progress we want to see). cwd defaults to the current directory."
    return subprocess.run(cmd, cwd=cwd, capture_output=capture, text=True)

def _git_out(args:list, cwd:str=None) -> str:
    "Stripped stdout of a `git` command, or '' if it failed -- for the small read-only queries (branch, HEAD sha, status)."
    r = _run(['git', *args], cwd=cwd)
    return r.stdout.strip() if r.returncode == 0 else ''

# %% ../nbs/06_publish.ipynb #eead6968
def _confirm(status:str, yes:bool) -> bool:
    "The proceed gate, shown after nbdev-clean/export so the review reflects generated changes too. Prints `status` (git status --short, so untracked files show as '??' and can't be silently missed by the later `git add -u`), then decides: `yes=True` proceeds outright (the -y override); on an interactive TTY it prompts 'Okay to proceed? [Y/n]'; on a non-TTY (a background run, an MCP/agent call) it returns False WITHOUT prompting -- the caller is meant to read the printed status and, if it looks right, re-invoke with yes=True. That single gate is thus both a human confirmation and an agent's read-and-authorize handoff."
    print(status or '(working tree clean)')
    if yes: return True
    if not sys.stdin.isatty():
        print("\n[non-interactive] Review the status above; re-run with yes=True (CLI: -y/--yes) to proceed.",
              file=sys.stderr)
        return False
    try: ans = input('Okay to proceed? [Y/n] ').strip().lower()
    except EOFError: return False
    return ans in ('', 'y', 'yes')

# %% ../nbs/06_publish.ipynb #f7b160c3
def _wait_for_ci(sha:str, # the pushed commit whose CI run to wait on
                 branch:str, # the branch it was pushed to (used to locate the run)
                 cwd:str=None, # repo directory
                 timeout:int=120, # max seconds to wait for the run to REGISTER after a push (GitHub can be slow to queue it, esp. a branch's first run). Once found, we then wait as long as the run itself takes.
                 poll:float=2.0 # seconds between registration checks
                 ) -> 'bool|None':
    "Block until the GitHub Actions run for `sha` finishes, via `gh`. Returns True (passed), False (failed), or None if it couldn't be determined -- and prints WHY: gh not installed, gh not authenticated (run `gh auth login` / set GH_TOKEN), or no run registered within `timeout`. A push doesn't register a run instantly, so first poll `gh run list` (up to `timeout`) for one whose headSha matches, then `gh run watch --exit-status` (streams live, exits nonzero iff the run failed). Auth/tooling errors short-circuit immediately rather than burning the whole timeout."
    if _run(['gh', '--version'], cwd=cwd).returncode != 0:
        print('gh CLI not found -- skipping CI wait.', file=sys.stderr); return None
    deadline = time.time() + timeout
    while True:
        r = _run(['gh', 'run', 'list', '--branch', branch, '--limit', '20',
                  '--json', 'databaseId,headSha', '--jq',
                  f'[.[]|select(.headSha=="{sha}")][0].databaseId'], cwd=cwd)
        if r.returncode != 0:
            err = (r.stderr or r.stdout or '').strip()
            if 'auth' in err.lower() or 'gh_token' in err.lower():
                print('gh is not authenticated -- run `gh auth login` (or set GH_TOKEN). Skipping CI wait.', file=sys.stderr)
            else:
                print(f'gh run list failed -- skipping CI wait:\n{err}', file=sys.stderr)
            return None
        rid = r.stdout.strip()
        if rid and rid != 'null': break
        if time.time() >= deadline:
            print(f'No CI run registered for {sha[:8]} within {timeout}s -- skipping CI wait.', file=sys.stderr)
            return None
        time.sleep(poll)
    print(f'Watching CI run {rid} ...')
    return _run(['gh', 'run', 'watch', rid, '--exit-status'], cwd=cwd, capture=False).returncode == 0

# %% ../nbs/06_publish.ipynb #833a1390
def publish(msg:str=None, # commit message; required only if there are changes to commit (prompted for on an interactive TTY if omitted). Ignored when the branch is already committed and just being shipped.
            prebuild:list=None, # shell commands to run before committing (regenerate build artifacts, run local checks, ...). Defaults to nbdev's ['nbdev-clean', 'nbdev-export', 'nbdev-readme'] (the last regenerates README.md from nbs/index.ipynb -- without it, index edits never reach the README); pass [] to skip, or e.g. ['ruff check .', 'pytest -q'] for a non-nbdev project. This venv's bin/ is prepended to PATH so bare tool names resolve to the project's own venv.
            dests:list=None, # publish destinations; only 'github' is implemented so far (pypi/conda later). Defaults to ['github'].
            merge:bool=True, # when on a non-main branch and CI passes, open a PR to main and merge it
            wait_ci:bool=True, # after pushing, wait for GitHub Actions to finish (forced on when a merge is needed -- a merge can't be gated without it)
            ci_timeout:int=120, # seconds to wait for the CI run to REGISTER after pushing before giving up (see _wait_for_ci); the run itself is then waited on for as long as it takes
            merge_method:str='merge', # how gh merges the PR: 'merge' | 'squash' | 'rebase'
            yes:bool=False, # skip the proceed prompt (the -y override); on a non-TTY without it, publish stops after showing git status so the caller can review and re-invoke
            cwd:str=None # repo directory (default: current directory)
            ) -> str:
    "Automate the edit->ship loop. In order: run `prebuild` (default nbdev-clean + nbdev-export + nbdev-readme), show `git status` and gate on it (see _confirm -- interactive prompt, or read-and-authorize for an agent), git add -u, commit (skipped if nothing staged), push; then for a 'github' dest wait for CI (see _wait_for_ci), and if it passes while you're on a non-main branch with merge=True, open a PR to main and merge it (merge_method), then leave you on an updated local main. Everything runs blocking/stop-on-error (don't proceed if a step failed) -- run publish itself in the background if you don't want to wait on CI. Progress is printed live; the returned string is a short final outcome. Only tracked files are staged (git add -u); new/untracked files show in the status review but aren't auto-added. If nothing is staged but the branch already has commits to ship, the commit step is skipped and it still pushes/CIs/merges. Knows nothing about nbdev specifically -- that's just the default prebuild."
    dests = dests if dests is not None else ['github']
    prebuild = prebuild if prebuild is not None else ['nbdev-clean', 'nbdev-export', 'nbdev-readme']
    if merge_method not in ('merge', 'squash', 'rebase'):
        return f"merge_method must be 'merge'|'squash'|'rebase', got {merge_method!r}."
    if 'github' not in dests:
        return f"Nothing to do -- only 'github' is implemented so far, got dests={dests}."

    def say(m): print(m, flush=True)  # live progress; the return value is just the final outcome (no re-dump of the log)

    # 1. prebuild: run each command in a shell, with this venv's bin/ ahead of PATH so a bare
    # `nbdev-clean` (etc.) resolves to the project's own venv rather than whatever's first globally.
    env = {**os.environ, 'PATH': f"{Path(sys.executable).parent}{os.pathsep}{os.environ.get('PATH', '')}"}
    for cmd in prebuild:
        r = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True, env=env)
        if r.returncode != 0:
            return f"prebuild step failed: {cmd!r} (rc={r.returncode}):\n{r.stderr or r.stdout}"
        say(f"[ok] {cmd}")

    # 2. show status and gate on it (may run prebuild twice across a non-TTY review re-run -- clean/export are idempotent)
    if not _confirm(_git_out(['status', '--short', '--branch'], cwd=cwd), yes):
        return "Stopped before committing (awaiting confirmation)."

    # 3. stage tracked changes only; commit iff something is actually staged
    if _run(['git', 'add', '-u'], cwd=cwd).returncode != 0:
        return "git add -u failed."
    if _run(['git', 'diff', '--cached', '--quiet'], cwd=cwd).returncode != 0:  # something staged
        if not msg:
            msg = input('Commit message: ').strip() if sys.stdin.isatty() else ''
            if not msg: return "Changes are staged but no commit message given (pass msg=..., or --msg)."
        r = _run(['git', 'commit', '-m', msg], cwd=cwd)
        if r.returncode != 0:
            return f"git commit failed:\n{r.stderr or r.stdout}"
        say(f"[ok] committed: {msg.splitlines()[0]}")
    else:
        say("[ok] nothing new to commit -- shipping already-committed work")

    branch = _git_out(['rev-parse', '--abbrev-ref', 'HEAD'], cwd=cwd)
    sha = _git_out(['rev-parse', 'HEAD'], cwd=cwd)

    # 4. push (-u origin HEAD works whether or not the branch already has an upstream)
    r = _run(['git', 'push', '-u', 'origin', 'HEAD'], cwd=cwd)
    if r.returncode != 0:
        return f"git push failed:\n{r.stderr or r.stdout}"
    say(f"[ok] pushed origin/{branch} ({sha[:8]})")

    # 5. CI
    on_main = branch in ('main', 'master')
    if not (wait_ci or (merge and not on_main)):
        return "Done (CI wait skipped)."
    ci = _wait_for_ci(sha, branch, cwd=cwd, timeout=ci_timeout)
    if ci is False:
        return "[FAIL] CI failed -- stopping. Run `slmn check_ci` for the failure logs."
    if ci is None:
        note = " (a PR merge needs a confirmed CI pass, so not merging)" if (merge and not on_main) else ""
        return f"[??] CI status unknown -- stopping.{note}"
    say("[ok] CI passed")

    # 6. non-main + merge -> PR to main and merge it
    if on_main or not merge:
        return "Done."
    title = (msg or _git_out(['log', '-1', '--pretty=%s'], cwd=cwd)).splitlines()[0]
    body = msg or _git_out(['log', '-1', '--pretty=%B'], cwd=cwd)
    cr = _run(['gh', 'pr', 'create', '--base', 'main', '--head', branch, '--title', title, '--body', body], cwd=cwd)
    out = cr.stderr + cr.stdout
    if cr.returncode != 0:
        if 'No commits between' in out:
            return "Nothing to ship: branch has no commits beyond main."
        if 'already exists' not in out:
            return f"gh pr create failed:\n{out}"
    mr = _run(['gh', 'pr', 'merge', branch, f'--{merge_method}', '--delete-branch'], cwd=cwd)
    if mr.returncode != 0:
        return f"gh pr merge failed:\n{mr.stderr or mr.stdout}"
    say(f"[ok] merged {branch} -> main ({merge_method}), branch deleted")
    _run(['git', 'checkout', 'main'], cwd=cwd)
    _run(['git', 'pull'], cwd=cwd)
    return f"Done -- {branch} merged to main; local now on updated main."
